require 'geokit'
include GeoKit::Geocoders

LOCATIONS = [
  "Birmingham, AL",
  "Hoover, AL",
  "Huntsville, AL",
  "Mobile, AL",
  "Montgomery, AL",
  "Tuscaloosa, AL",
  "Anchorage, AK",
  "Avondale, AZ",
  "Chandler, AZ",
  "Gilbert, AZ",
  "Glendale, AZ",
  "Mesa, AZ",
  "Peoria, AZ",
  "Phoenix, AZ",
  "Scottsdale, AZ",
  "Surprise, AZ",
  "Tempe, AZ",
  "Tucson, AZ",
  "Yuma, AZ, AK",
  "Fayetteville, AK",
  "Fort Smith, AK",
  "Jonesboro, AK",
  "Little Rock, AK",
  "Springdale, AK, CA",
  "Alameda, CA",
  "Alhambra, CA",
  "Anaheim, CA",
  "Antioch, CA",
  "Apple Valley, CA",
  "Bakersfield, CA",
  "Baldwin Park, CA",
  "Bellflower, CA",
  "Berkeley, CA",
  "Buena Park, CA",
  "Burbank, CA",
  "Carlsbad, CA",
  "Carson, CA",
  "Chico, CA",
  "Chino, CA",
  "Chino Hills, CA",
  "Chula Vista, CA",
  "Citrus Heights, CA",
  "Clovis, CA",
  "Compton, CA",
  "Concord, CA",
  "Corona, CA",
  "Costa Mesa, CA",
  "Daly City, CA",
  "Downey, CA",
  "El Cajon, CA",
  "Elk Grove, CA",
  "El Monte, CA",
  "Escondido, CA",
  "Fairfield, CA",
  "Folsom, CA",
  "Fontana, CA",
  "Fremont, CA",
  "Fresno, CA",
  "Fullerton, CA",
  "Garden Grove, CA",
  "Hawthorne, CA",
  "Hayward, CA",
  "Hemet, CA",
  "Hesperia, CA",
  "Huntington Beach, CA",
  "Indio, CA",
  "Inglewood, CA",
  "Irvine, CA",
  "Lake Forest, CA",
  "Lakewood, CA",
  "Lancaster, CA",
  "Livermore, CA",
  "Long Beach, CA",
  "Los Angeles, CA",
  "Lynwood, CA",
  "Manteca, CA",
  "Menifee, CA",
  "Merced, CA",
  "Milpitas, CA",
  "Mission Viejo, CA",
  "Modesto, CA",
  "Moreno Valley, CA",
  "Mountain View, CA",
  "Murrieta, CA",
  "Napa, CA",
  "Newport Beach, CA",
  "Norwalk, CA",
  "Oakland, CA",
  "Oceanside, CA",
  "Ontario, CA",
  "Orange, CA",
  "Oxnard, CA",
  "Palmdale, CA",
  "Pasadena, CA",
  "Perris, CA",
  "Pleasanton, CA",
  "Pomona, CA",
  "Rancho Cucamonga, CA",
  "Redding, CA",
  "Redlands, CA",
  "Redondo Beach, CA",
  "Redwood City, CA",
  "Rialto, CA",
  "Richmond, CA",
  "Riverside, CA",
  "Roseville, CA",
  "Sacramento, CA",
  "Salinas, CA",
  "San Bernardino, CA",
  "San Diego, CA",
  "San Buenaventura (Ventura), CA",
  "San Francisco, CA",
  "San Jose, CA",
  "San Leandro, CA",
  "San Marcos, CA",
  "San Mateo, CA",
  "San Ramon, CA",
  "Santa Ana, CA",
  "Santa Barbara, CA",
  "Santa Clara, CA",
  "Santa Clarita, CA",
  "Santa Maria, CA",
  "Santa Monica, CA",
  "Santa Rosa, CA",
  "Simi Valley, CA",
  "South Gate, CA",
  "Stockton, CA",
  "Sunnyvale, CA",
  "Temecula, CA",
  "Thousand Oaks, CA",
  "Torrance, CA",
  "Tracy, CA",
  "Turlock, CA",
  "Tustin, CA",
  "Union City, CA",
  "Upland, CA",
  "Vacaville, CA",
  "Vallejo, CA",
  "Victorville, CA",
  "Visalia, CA",
  "Vista, CA",
  "West Covina, CA",
  "Westminster, CA",
  "Whittier, CA, CO",
  "Arvada, CO",
  "Aurora, CO",
  "Boulder, CO",
  "Centennial, CO",
  "Colorado Springs, CO",
  "Denver, CO",
  "Fort Collins, CO",
  "Greeley, CO",
  "Longmont, CO",
  "Loveland, CO",
  "Pueblo, CO",
  "Thornton, CO, CT",
  "Bridgeport, CT",
  "Danbury, CT",
  "Hartford, CT",
  "New Britain, CT",
  "New Haven, CT",
  "Stamford, CT",
  "Waterbury, CT",
  "Wilmington, DE",
  "Washington, DC, FL",
  "Boca Raton, FL",
  "Boynton Beach, FL",
  "Cape Coral, FL",
  "Clearwater, FL",
  "Coral Springs, FL",
  "Davie, FL",
  "Deerfield Beach, FL",
  "Deltona, FL",
  "Fort Lauderdale, FL",
  "Gainesville, FL",
  "Hialeah, FL",
  "Hollywood, FL",
  "Jacksonville, FL",
  "Lakeland, FL",
  "Largo, FL",
  "Lauderhill, FL",
  "Melbourne, FL",
  "Miami, FL",
  "Miami Beach, FL",
  "Miami Gardens, FL",
  "Miramar, FL",
  "Orlando, FL",
  "Palm Bay, FL",
  "Palm Coast, FL",
  "Pembroke Pines, FL",
  "Plantation, FL",
  "Pompano Beach, FL",
  "Port St. Lucie, FL",
  "St. Petersburg, FL",
  "Sunrise, FL",
  "Tallahassee, FL",
  "Tampa, FL",
  "West Palm Beach, FL",
  "Albany, GA",
  "Athens, GA",
  "Atlanta, GA",
  "Augusta, GA",
  "Columbus, GA",
  "Johns Creek, GA",
  "Macon, GA",
  "Roswell, GA",
  "Sandy Springs, GA",
  "Savannah, GA",
  "Warner Robins, GA",
  "Honolulu, HI",
  "Boise City, ID",
  "Meridian, ID",
  "Nampa, ID",
  "Arlington Heights, IL",
  "Bloomington, IL",
  "Bolingbrook, IL",
  "Champaign, IL",
  "Chicago, IL",
  "Cicero, IL",
  "Decatur, IL",
  "Elgin, IL",
  "Evanston, IL",
  "Joliet, IL",
  "Naperville, IL",
  "Palatine, IL",
  "Rockford, IL",
  "Schaumburg, IL",
  "Sioux City, IL",
  "Springfield, IL",
  "Waukegan, IL, ID",
  "Carmel, ID",
  "Evansville, ID",
  "Fishers, ID",
  "Fort Wayne, ID",
  "Gary, ID",
  "Hammond, ID",
  "Indianapolis, ID",
  "Lafayette, ID",
  "Muncie, ID",
  "South Bend, ID",
  "Cedar Rapids, IA",
  "Davenport, IA",
  "Des Moines, IA",
  "Iowa City, IA",
  "Waterloo, IA",
  "Kansas City",
  "Lawrence, KY",
  "Olathe, KY",
  "Overland Park, KY",
  "Topeka, KY",
  "Wichita, KY",
  "Lexington, KY",
  "Louisville, KY",
  "Baton Rouge, LA",
  "Kenner, LA",
  "Lake Charles, LA",
  "New Orleans, LA",
  "Shreveport, LA",
  "Portland, ME",
  "Baltimore, MD",
  "Boston, MA",
  "Brockton, MA",
  "Cambridge, MA",
  "Fall River, MA",
  "Lowell, MA",
  "Lynn, MA",
  "New Bedford, MA",
  "Newton, MA",
  "Quincy, MA",
  "Somerville, MA",
  "Worcester, MA",
  "Ann Arbor, MI",
  "Dearborn, MI",
  "Detroit, MI",
  "Farmington Hills, MI",
  "Flint, MI",
  "Grand Rapids, MI",
  "Kalamazoo, MI",
  "Lansing, MI",
  "Livonia, MI",
  "Rochester Hills, MI",
  "Southfield, MI",
  "Sterling Heights, MI",
  "Troy, MI",
  "Warren, MI",
  "Westland, MI",
  "Wyoming, MI, MN",
  "Brooklyn Park, MN",
  "Duluth, MN",
  "Minneapolis, MN",
  "Plymouth, MN",
  "Rochester, MN",
  "St. Paul, MN",
  "Gulfport, MI",
  "Jackson, MI",
  "Columbia, MO",
  "Independence, MO",
  "Lee's Summit, MO",
  "O'Fallon, MO",
  "St. Joseph, MO",
  "St. Louis, MO",
  "Billings, MT",
  "Missoula, MT",
  "Lincoln, NE",
  "Omaha, NE",
  "Henderson, NV",
  "Las Vegas, NV",
  "North Las Vegas, NV",
  "Reno, NV",
  "Sparks, NV",
  "Manchester, NH",
  "Nashua, NH",
  "Camden, NJ",
  "Clifton, NJ",
  "Elizabeth, NJ",
  "Jersey City, NJ",
  "Newark, NJ",
  "Passaic, NJ",
  "Paterson, NJ",
  "Trenton, NJ",
  "Albuquerque, NM",
  "Las Cruces, NM",
  "Rio Rancho, NM",
  "Santa Fe, NM",
  "Buffalo, NY",
  "Mount Vernon, NY",
  "New Rochelle, NY",
  "New York, NY",
  "Schenectady, NY",
  "Syracuse, NY",
  "Yonkers, NY",
  "Asheville, NC",
  "Cary, NC",
  "Charlotte, NC",
  "Durham, NC",
  "Gastonia, NC",
  "Greensboro, NC",
  "High Point, NC",
  "Raleigh, NC",
  "Greenville, NC",
  "Fargo, ND",
  "Winston-Salem, NC, OH",
  "Akron, OH",
  "Canton, OH",
  "Cincinnati, OH",
  "Cleveland, OH",
  "Dayton, OH",
  "Parma, OH",
  "Toledo, OH",
  "Youngstown, OH",
  "Broken Arrow, OK",
  "Edmond, OK",
  "Lawton, OK",
  "Norman, OK",
  "Oklahoma City, OK",
  "Tulsa, OK",
  "Beaverton, OR",
  "Bend, OR",
  "Eugene, OR",
  "Gresham, OR",
  "Hillsboro, OR",
  "Medford, OR",
  "Salem, OR",
  "Allentown, PA",
  "Bethlehem, PA",
  "Erie, PA",
  "Philadelphia, PA",
  "Pittsburgh, PA",
  "Reading, PA",
  "Scranton, PA",
  "Cranston, RI",
  "Pawtucket, RI",
  "Providence, RI",
  "Warwick, RI",
  "Columbia, SC"
  "Charleston, SC",
  "Mount Pleasant, SC",
  "Rock Hill, SC",
  "North Charleston, SC",
  "Rapid City, SD",
  "Sioux Falls, SD",
  "Chattanooga, TN",
  "Clarksville, TN",
  "Knoxville, TN",
  "Memphis, TN",
  "Nashville, TN",
  "Murfreesboro, TN",
  "Pearland, TX",
  "Plano, TX",
  "Murfreesboro, TX",
  "Nashville, TX",
  "Abilene, TX",
  "Allen, TX",
  "Amarillo, TX",
  "Arlington, TX",
  "Austin, TX",
  "Baytown, TX",
  "Beaumont, TX",
  "Brownsville, TX",
  "Bryan, TX",
  "Carrollton, TX",
  "College Station, TX",
  "Corpus Christi, TX",
  "Dallas, TX",
  "Denton, TX",
  "Edinburg, TX",
  "El Paso, TX",
  "Fort Worth, TX",
  "Frisco, TX",
  "Garland, TX",
  "Grand Prairie, TX",
  "Houston, TX",
  "Irving, TX",
  "Killeen, TX",
  "Laredo, TX",
  "League City, TX",
  "Lewisville, TX",
  "Longview, TX",
  "Lubbock, TX",
  "McAllen, TX",
  "McKinney, TX",
  "Mesquite, TX",
  "Midland, TX",
  "Mission, TX",
  "Missouri City, TX",
  "Odessa, TX",
  "Pharr, TX",
  "Richardson, TX",
  "Round Rock, TX",
  "San Angelo, TX",
  "San Antonio, TX",
  "Sugar Land, TX",
  "Tyler, TX",
  "Waco, TX",
  "Wichita Falls, TX",
  "Layton, UT",
  "Ogden, UT",
  "Orem, UT",
  "Provo, UT",
  "St. George, UT",
  "Salt Lake City, UT",
  "Sandy, UT",
  "West Jordan, UT",
  "West Valley City, UT",
  "Burlington, VT",
  "Alexandria, VA",
  "Chesapeake, VA",
  "Hampton, VA",
  "Lynchburg, VA",
  "Newport News, VA",
  "Norfolk, VA",
  "Portsmouth, VA",
  "Roanoke, VA",
  "Suffolk, VA",
  "Virginia Beach, VA",
  "Auburn, WA",
  "Bellevue, WA",
  "Bellingham, WA",
  "Everett, WA",
  "Federal Way, WA",
  "Kennewick, WA",
  "Kent, WA",
  "Renton, WA",
  "Seattle, WA",
  "Spokane, WA",
  "Spokane Valley, WA",
  "Tacoma, WA",
  "Vancouver, WA",
  "Yakima, WA",
  "Charleston, WV",
  "Appleton, WI",
  "Green Bay, WI",
  "Kenosha, WI",
  "Madison, WI",
  "Milwaukee, WI",
  "Racine, WI",
  "Waukesha, WI",
  "Cheyenne, WY",
]
